seed: 42
solution: '00000000'
minGenomeLength: 5
maxGenomeLength: 10
maxGeneration: 3000
populationSize: 200
tournamentSize: 6
mutationRate: 0.3
bitFlipRate: 0.7
bitAddRate: 0.2
bitRemoveRate: 0.1
crossoverRate: 0.7
lengthPunishingFactor: 0.5
selectionStrategy: TOURNAMENT
mutationTargetStrategy: CHILDREN
crossoverStrategy: ARITHMETIC
crossoverLeftoverStrategy: KEEP_ALL_OR_NOTHING_RANDOMLY
lengthPunishingStrategy: LINEAR
