seed: 42
solution: '00000000'
minGenomeLength: 5
maxGenomeLength: 10
maxGeneration: 3000
populationSize: 200
tournamentSize: 6
mutationRate: 0.05
bitFlipRate: 0.02
bitAddRate: 0.01
bitRemoveRate: 0.01
crossoverRate: 0.7
lengthPunishingFactor: 0.5
selectionStrategy: ROULETTE
mutationTargetStrategy: BOTH
crossoverStrategy: ONE_POINT
crossoverLeftoverStrategy: KEEP_ONE_OR_NOT_RANDOMLY
lengthPunishingStrategy: LINEAR
