seed: 42
solution: '00000000'
minGenomeLength: 5
maxGenomeLength: 10
maxGeneration: 3000
populationSize: 200
tournamentSize: 6
mutationRate: 0.3
bitFlipRate: 0.7
bitAddRate: 0.2
bitRemoveRate: 0.1
crossoverRate: 0.7
lengthPunishingFactor: 0.5
selectionStrategy: ELITISM
mutationTargetStrategy: PARENTS
crossoverStrategy: UNIFORM
crossoverLeftoverStrategy: KEEP_ONLY_FROM_FITTEST_PARENT
lengthPunishingStrategy: LINEAR
